#!/usr/bin/env python3
"""
AST Visualization Tool

Visualizes AST structures from pickle files generated by mtl-owl-tool.py.
Outputs are saved to code/results/visualize/ directory.
"""

import pickle as pkl
import sys
import os
from pathlib import Path
from graphviz import Digraph

# Add parent directory for imports
current_dir = os.path.dirname(os.path.abspath(__file__))
sys.path.append(current_dir)

# Import from pytelo_modified
from pytelo_modified.stl import Operation, RelOperation, STLFormula

class ASTVisualizer:
    def __init__(self):
        self.node_counter = 0
        self.graph = None
        
    def get_node_label(self, node):
        """Generate a human-readable label for each node type."""
        if node.op == Operation.PRED:
            rel_symbol = {
                RelOperation.GT: ">",
                RelOperation.LT: "<",
                RelOperation.GE: "≥",
                RelOperation.LE: "≤",
                RelOperation.EQ: "=",
                RelOperation.NQ: "≠"
            }.get(node.relation, "?")
            return f"{node.variable} {rel_symbol} {node.threshold}"
            
        elif node.op == Operation.VAR:
            return f"Var: {node.variable}"
            
        elif node.op == Operation.BOOL:
            return "True" if node.value else "False"
            
        elif node.op == Operation.ALWAYS:
            return f"G[{node.low}, {node.high}]"
            
        elif node.op == Operation.EVENT:
            return f"F[{node.low}, {node.high}]"
            
        elif node.op == Operation.UNTIL:
            return f"U[{node.low}, {node.high}]"
            
        elif node.op == Operation.NOT:
            return "¬ (NOT)"
            
        elif node.op == Operation.AND:
            return "∧ (AND)"
            
        elif node.op == Operation.OR:
            return "∨ (OR)"
            
        elif node.op == Operation.IMPLIES:
            return "→ (IMPLIES)"
            
        else:
            return f"Op: {node.op}"
    
    def get_node_shape(self, node):
        """Return appropriate shape for different node types."""
        if node.op in (Operation.PRED, Operation.VAR, Operation.BOOL):
            return "box"
        elif node.op in (Operation.ALWAYS, Operation.EVENT, Operation.UNTIL):
            return "diamond"
        else:
            return "ellipse"
    
    def get_node_color(self, node):
        """Return color scheme for different node types."""
        color_map = {
            Operation.PRED: "lightblue",
            Operation.VAR: "lightgreen",
            Operation.BOOL: "lightyellow",
            Operation.AND: "lightcoral",
            Operation.OR: "lightpink",
            Operation.NOT: "lightgray",
            Operation.IMPLIES: "plum",
            Operation.ALWAYS: "lightsteelblue",
            Operation.EVENT: "palegreen",
            Operation.UNTIL: "peachpuff"
        }
        return color_map.get(node.op, "white")
    
    def visualize_node(self, node, parent_id=None):
        """Recursively visualize nodes and their connections."""
        if node is None:
            return
            
        # Create unique node ID
        node_id = f"node_{self.node_counter}"
        self.node_counter += 1
        
        # Add node to graph
        label = self.get_node_label(node)
        shape = self.get_node_shape(node)
        color = self.get_node_color(node)
        
        self.graph.node(node_id, label=label, shape=shape, 
                       style="filled", fillcolor=color, fontsize="10")
        
        # Connect to parent if exists
        if parent_id:
            self.graph.edge(parent_id, node_id)
        
        # Handle different node types
        if hasattr(node, 'child') and node.child:
            self.visualize_node(node.child, node_id)
            
        if hasattr(node, 'left') and node.left:
            self.visualize_node(node.left, node_id)
            
        if hasattr(node, 'right') and node.right:
            self.visualize_node(node.right, node_id)
            
        if hasattr(node, 'children') and node.children:
            for i, child in enumerate(node.children):
                self.visualize_node(child, node_id)
    
    def visualize_ast(self, ast_root, output_path):
        """Create and render the visualization."""
        self.node_counter = 0
        self.graph = Digraph(comment='AST Visualization')
        self.graph.attr(rankdir='TB')  # Top to Bottom layout
        self.graph.attr('node', fontname='Arial')
        self.graph.attr('edge', fontname='Arial')
        
        # Start visualization from root
        self.visualize_node(ast_root)
        
        # Render to file (without extension as graphviz adds it)
        output_path_no_ext = str(output_path).rsplit('.', 1)[0] if '.' in str(output_path) else str(output_path)
        self.graph.render(output_path_no_ext, format='png', cleanup=True)
        # self.graph.render(output_path_no_ext, format='pdf', cleanup=True)
        
        return self.graph

def load_and_visualize_pkl(pkl_path, output_dir=None):
    """Load a PKL file and visualize the AST."""
    try:
        # Default output directory
        if output_dir is None:
            output_dir = os.path.join(current_dir, 'results', 'visualize')
        
        # Create output directory if it doesn't exist
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        
        # Load the AST from pickle file
        with open(pkl_path, 'rb') as f:
            ast_data = pkl.load(f)
        
        # Handle different pickle formats
        if isinstance(ast_data, dict):
            # If it's a dict from from-ontology command, extract the first AST
            if ast_data:
                first_key = list(ast_data.keys())[0]
                ast = ast_data[first_key]
                print(f"Successfully loaded AST for requirement '{first_key}' from {pkl_path}")
            else:
                raise ValueError("Empty dictionary in pickle file")
        else:
            # Direct AST object
            ast = ast_data
            print(f"Successfully loaded AST from {pkl_path}")
        
        # Generate output name based on input file
        base_name = os.path.splitext(os.path.basename(pkl_path))[0]
        output_name = f"ast_viz_{base_name}"
        output_path = os.path.join(output_dir, output_name)
        
        # Create visualizer and generate visualization
        visualizer = ASTVisualizer()
        graph = visualizer.visualize_ast(ast, output_path)
        
        print(f"Visualization saved as:")
        print(f"  - {output_path}.png")
        # print(f"  - {output_path}.pdf")
        
        # Also print text representation
        print("\n--- AST Text Structure ---")
        print_ast_text(ast)
        
        return graph
        
    except Exception as e:
        print(f"Error loading or visualizing {pkl_path}: {e}")
        import traceback
        traceback.print_exc()
        return None

def print_ast_text(node, indent=0):
    """Print text representation of AST."""
    indent_str = "  " * indent
    
    if node.op == Operation.PRED:
        rel_symbol = {
            RelOperation.GT: ">",
            RelOperation.LT: "<",
            RelOperation.GE: ">=",
            RelOperation.LE: "<=",
            RelOperation.EQ: "=",
            RelOperation.NQ: "!="
        }.get(node.relation, "?")
        print(f"{indent_str}PREDICATE: {node.variable} {rel_symbol} {node.threshold}")
    elif node.op == Operation.VAR:
        print(f"{indent_str}VARIABLE: {node.variable}")
    elif node.op == Operation.BOOL:
        print(f"{indent_str}BOOLEAN: {node.value}")
    elif node.op == Operation.ALWAYS:
        print(f"{indent_str}GLOBALLY [{node.low}, {node.high}]:")
        if node.child:
            print_ast_text(node.child, indent + 1)
    elif node.op == Operation.EVENT:
        print(f"{indent_str}EVENTUALLY [{node.low}, {node.high}]:")
        if node.child:
            print_ast_text(node.child, indent + 1)
    elif node.op == Operation.UNTIL:
        print(f"{indent_str}UNTIL [{node.low}, {node.high}]:")
        print(f"{indent_str}  Left:")
        if node.left:
            print_ast_text(node.left, indent + 2)
        print(f"{indent_str}  Right:")
        if node.right:
            print_ast_text(node.right, indent + 2)
    elif node.op == Operation.NOT:
        print(f"{indent_str}NOT:")
        if node.child:
            print_ast_text(node.child, indent + 1)
    elif node.op == Operation.AND:
        print(f"{indent_str}AND:")
        if hasattr(node, 'children'):
            for i, child in enumerate(node.children):
                print(f"{indent_str}  Child {i+1}:")
                print_ast_text(child, indent + 2)
    elif node.op == Operation.OR:
        print(f"{indent_str}OR:")
        if hasattr(node, 'children'):
            for i, child in enumerate(node.children):
                print(f"{indent_str}  Child {i+1}:")
                print_ast_text(child, indent + 2)
    elif node.op == Operation.IMPLIES:
        print(f"{indent_str}IMPLIES:")
        print(f"{indent_str}  Left:")
        if node.left:
            print_ast_text(node.left, indent + 2)
        print(f"{indent_str}  Right:")
        if node.right:
            print_ast_text(node.right, indent + 2)

def compare_and_visualize(pkl1_path, pkl2_path, output_dir=None):
    """Load two PKL files and create side-by-side visualization."""
    try:
        # Default output directory
        if output_dir is None:
            output_dir = os.path.join(current_dir, 'results', 'visualize')
        
        # Create output directory if it doesn't exist
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        
        # Load both ASTs
        with open(pkl1_path, 'rb') as f:
            ast1_data = pkl.load(f)
        with open(pkl2_path, 'rb') as f:
            ast2_data = pkl.load(f)
        
        # Handle different pickle formats
        if isinstance(ast1_data, dict):
            first_key = list(ast1_data.keys())[0]
            ast1 = ast1_data[first_key]
        else:
            ast1 = ast1_data
            
        if isinstance(ast2_data, dict):
            first_key = list(ast2_data.keys())[0]
            ast2 = ast2_data[first_key]
        else:
            ast2 = ast2_data
        
        # Create combined graph
        graph = Digraph(comment='AST Comparison')
        graph.attr(rankdir='TB')
        graph.attr('graph', compound='true')
        
        # Create subgraphs for each AST
        with graph.subgraph(name='cluster_0') as sg1:
            sg1.attr(label=f'AST 1: {os.path.basename(pkl1_path)}')
            sg1.attr(style='filled', color='lightgrey')
            visualizer1 = ASTVisualizer()
            visualizer1.graph = sg1
            visualizer1.visualize_node(ast1)
        
        with graph.subgraph(name='cluster_1') as sg2:
            sg2.attr(label=f'AST 2: {os.path.basename(pkl2_path)}')
            sg2.attr(style='filled', color='lightblue')
            visualizer2 = ASTVisualizer()
            visualizer2.graph = sg2
            visualizer2.node_counter = 1000  # Offset to avoid ID conflicts
            visualizer2.visualize_node(ast2)
        
        output_name = "ast_comparison"
        output_path = os.path.join(output_dir, output_name)
        
        graph.render(output_path, format='png', cleanup=True)
        # graph.render(output_path, format='pdf', cleanup=True)
        
        print(f"Comparison visualization saved as:")
        print(f"  - {output_path}.png")
        # print(f"  - {output_path}.pdf")
        
    except Exception as e:
        print(f"Error comparing ASTs: {e}")
        import traceback
        traceback.print_exc()

def visualize_directory(directory, output_dir=None):
    """Visualize all PKL files in a directory."""
    pkl_files = [f for f in os.listdir(directory) if f.endswith('.pkl')]
    
    if not pkl_files:
        print(f"No .pkl files found in {directory}")
        return
    
    print(f"Found {len(pkl_files)} PKL files to visualize")
    
    for pkl_file in sorted(pkl_files):
        pkl_path = os.path.join(directory, pkl_file)
        print(f"\n--- Processing {pkl_file} ---")
        load_and_visualize_pkl(pkl_path, output_dir)

def main():
    """Main entry point for the visualization tool."""
    if len(sys.argv) < 2:
        print("AST Visualization Tool")
        print("\nUsage:")
        print("  python visualize.py <pkl_file>                    # Visualize single AST")
        print("  python visualize.py <pkl_file1> <pkl_file2>       # Compare two ASTs")
        print("  python visualize.py --dir <directory>              # Visualize all PKL files in directory")
        print("\nOutput files are saved to: code/results/visualize/")
        print("\nExamples:")
        print("  python visualize.py results/plkFiles/test_ast.pkl")
        print("  python visualize.py results/plkFiles/ast1.pkl results/plkFiles/ast2.pkl")
        print("  python visualize.py --dir results/plkFiles")
        sys.exit(1)
    
    # Default output directory
    output_dir = os.path.join(current_dir, 'results', 'visualize')
    
    if sys.argv[1] == "--dir" and len(sys.argv) >= 3:
        # Visualize all PKL files in directory
        directory = sys.argv[2]
        visualize_directory(directory, output_dir)
            
    elif len(sys.argv) == 2:
        # Single file visualization
        load_and_visualize_pkl(sys.argv[1], output_dir)
        
    elif len(sys.argv) == 3:
        # Compare two files
        compare_and_visualize(sys.argv[1], sys.argv[2], output_dir)
    
    else:
        print("Invalid arguments. Run 'python visualize.py' for usage information.")
        sys.exit(1)

if __name__ == "__main__":
    main()